<?php

namespace App\Web\Claim;

readonly class ClaimDto
{
    public function __construct(
        public string $id,
        public string $msme_id,
        public string $claim_type_id,
        public string $snp_id,
        public string $team_registration_id,
        public string $msme_udyam_number,
        public string $msme_classification,
        public string $msme_name,
        public string $msme_category,
        public string $msme_transaction_type,
        //public string $seller_provider_id,
        public string $bpp_id,
        public string $catalogue_type,
        public string $onboarding_date,
        public string $number_of_orders,
        public string $no_of_transactions,
        public string $minimum_order_value,
        public string $number_of_skus,
        public string $total_gmv,
        public string $net_sales,
        public string $total_commission,
        public string $declaration_dual_claim,
        public string $declaration_eligibility,
        public string $declaration_authorization,
        public int $status,
        public int | string $is_sent_ondc,
        public int $ondc_review_status,
        public string $udin_number,
        public string $remarks,
        public ?string $ondc_order_id1 = null,
        public ?string $ondc_order_id2 = null,
        public ?string $ondc_invoice_number1 = null,
        public ?string $ondc_invoice_number2 = null,
        public ?string $ondc_invoice_date1 = null,
        public ?string $ondc_invoice_date2 = null,
        public ?array $claim_documents = null,
		public string $target_audience,
		public ?string $campaign_period = null,
		public ?string $campaign_duration = null,
		public ?string $msme_email = null,
		public ?string $msme_mobile = null,
		public ?string $msme_address = null,
		public ?string $msme_state = null,
		public ?string $msme_district = null,
		public ?string $design_type = null,
        public ?string $date_of_design_request = null,
        public ?string $date_of_design_delivery = null,
        public ?string $design_cost = null,
        public ?string $single_use_plastic = null,
        public ?string $description = null,
        public ?string $packaging_remarks = null,

        public ?string $organisation_id_seller_np = null,
        public ?string $organisation_id_lsp = null,
        public ?string $seller_np_configuration = null,
        public ?string $configuration= null,
        public ?string $ondc_seller_network_id = null,
        public ?string $seller_credential_report = null,
        public ?string $catalogue_score_report = null,
        public ?string $date_of_onboarding = null,
        public ?string $date_of_sku_update = null,
        public ?array $order_details = null,
    	
    ) {}

    public static function fromArray(array $data): self
    {
        return new self(
            $data['id'] ?? '',
            $data['msme_id'] ?? '',
            $data['claim_type_id'] ?? '',
            $data['snp_id'] ?? '',
            $data['team_registration_id'] ?? '',
            $data['msme_udyam_number'] ?? '',
            $data['msme_classification'] ?? '',
            $data['msme_name'] ?? '',
            $data['msme_category'] ?? '',
            $data['msme_transaction_type'] ?? '',
            //$data['seller_provider_id'] ?? '',
            $data['bpp_id'] ?? '',
            $data['catalogue_type'] ?? '',
            $data['onboarding_date'] ?? '',
            $data['number_of_orders'] ?? '',
            $data['no_of_transactions'] ?? '',
            $data['minimum_order_value'] ?? '',
            $data['number_of_skus'] ?? '',
            $data['total_gmv'] ?? '',
            $data['net_sales'] ?? '',
            $data['total_commission'] ?? '',
            $data['declaration_dual_claim'] ?? '',
            $data['declaration_eligibility'] ?? '',
            $data['declaration_authorization'] ?? '',
            isset($data['status']) ? (int)$data['status'] : 0,
            isset($data['is_sent_ondc']) ? (int)$data['is_sent_ondc'] : 1,
            isset($data['ondc_review_status']) ? (int) 1 : 1,
            $data['udin_number'] ?? '',
            $data['remarks'] ?? '',
            $data['ondc_order_id1'] ?? null,
            $data['ondc_order_id2'] ?? null,
            $data['ondc_invoice_number1'] ?? null,
            $data['ondc_invoice_number2'] ?? null,
            $data['ondc_invoice_date1'] ?? null,
            $data['ondc_invoice_date2'] ?? null,
            $data['claim_documents'] ?? null,
			$data['target_audience'] ?? '',
            $data['campaign_period'] ?? null,
            $data['campaign_duration'] ?? null,
            $data['msme_email'] ?? null,
            $data['msme_mobile'] ?? null,
            $data['msme_address'] ?? null,
            $data['msme_state'] ?? null,
            $data['msme_district'] ?? null,
            $data['design_type'] ?? null,
            $data['date_of_design_request'] ?? null,
            $data['date_of_design_delivery'] ?? null,
            $data['design_cost'] ?? null,
            $data['single_use_plastic'] ?? null,
            $data['description'] ?? null,
            $data['packaging_remarks'] ?? null,

            $data['organisation_id_seller_np'] ?? null,
            $data['organisation_id_lsp'] ?? null,
            $data['seller_np_configuration'] ?? null,
            $data['configuration'] ?? null,
            $data['ondc_seller_network_id'] ?? null,
            $data['seller_credential_report'] ?? null,
            $data['catalogue_score_report'] ?? null,
            $data['date_of_onboarding'] ?? null,
            $data['date_of_sku_update'] ?? null,
            
            $data['order_details'] ?? null,
        );
    }
}
